<?php
use think\Env;
return array (
  'db' => array (
    'type' => Env::get('db_type', 'mysql'),
    'path' => Env::get('db_path', ''),
    'server' => Env::get('db_host', '127.0.0.1'),
    'port' => Env::get('db_port', '3306'),
    'name' => Env::get('db_name', 'maccms10'),
    'user' => Env::get('db_user', 'root'),
    'pass' => Env::get('db_pass', 'root'),
    'tablepre' => Env::get('db_prefix', 'mac_'),
    'backup_path' => Env::get('db_backup_path', './application/data/backup/database/'),
    'part_size' => Env::get('db_part_size', 20971520),
    'compress' => Env::get('db_compress', 1),
    'compress_level' => Env::get('db_compress_level', 4),
  ),
  'site' => array (
    'site_name' => Env::get('site_name', '免费短剧电影电视剧、小说漫画 - 最新全集在线观看'),
    'site_url' => Env::get('site_url', 'localhost:9985'),
    'site_wapurl' => Env::get('site_wapurl', 'localhost:9985'),
    'site_keywords' => Env::get('site_keywords', '短视频,搞笑视频,视频分享,免费视频,在线视频,预告片'),
    'site_description' => Env::get('site_description', '提供最新最快的视频分享数据'),
    'site_icp' => Env::get('site_site_icp', 'icp123'),
    'site_qq' => Env::get('site_site_qq', '123456'),
    'site_email' => Env::get('site_site_email', '123456@test.cn'),
    'install_dir' => Env::get('site_install_dir', '/'),
    'site_logo' => Env::get('site_site_logo', 'static/images/logo.jpg'),
    'site_waplogo' => Env::get('site_site_waplogo', 'static/images/logo.jpg'),
    'site_banner' => Env::get('site_site_banner', ''),
    'site_app_launch_image' => Env::get('site_site_app_launch_image', ''),
    'template_dir' => Env::get('site_template', 'default'),
    'html_dir' => Env::get('site_html_dir', 'html'),
    'site_polyfill' => Env::get('site_site_polyfill', '0'),
    'mob_status' => Env::get('site_mob_status', '0'),
    'mob_template_dir' => Env::get('site_mob_template_dir', 'default'),
    'mob_html_dir' => Env::get('site_mob_html_dir', 'html'),
    'site_tj' => Env::get('site_tj', '统计代码'),
    'site_status' => Env::get('site_site_status', '1'),
    'site_close_tip' => Env::get('site_site_close_tip', '站点暂时关闭，请稍后访问'),
    'mainland_ip_limit' => Env::get('site_mainland_ip_limit', '0'),
    'new_version' => Env::get('site_new_version', ''),
    'ads_dir' => Env::get('site_ads_dir', 'ads'),
    'mob_ads_dir' => Env::get('site_mob_ads_dir', 'ads'),
  ),
  'app' => array (
    'pathinfo_depr' => Env::get('app_pathinfo_depr', '/'),
    'suffix' => Env::get('app_suffix', 'html'),
    'popedom_filter' => Env::get('app_popedom_filter', '0'),
    'cache_type' => Env::get('app_cache_type', 'file'),
    'cache_host' => Env::get('app_cache_host', '127.0.0.1'),
    'cache_port' => Env::get('app_cache_port', '6379'),
    'cache_username' => Env::get('app_cache_username', ''),
    'cache_password' => Env::get('app_cache_password', ''),
    'cache_db' => Env::get('app_cache_db', '0'),
    'cache_flag' => Env::get('app_cache_flag', 'a6bcf9aa58'),
    'cache_core' => Env::get('app_cache_core', '1'),
    'cache_time' => Env::get('app_cache_time', '3600'),
    'cache_page' => Env::get('app_cache_page', '0'),
    'cache_time_page' => Env::get('app_cache_time_page', '3600'),
    'compress' => Env::get('app_compress', '0'),
    'input_type' => Env::get('app_input_type', '1'),
    'ajax_page' => Env::get('app_ajax_page', '0'),
    'wall_filter' => Env::get('app_wall_filter', '0'),
    'show' => Env::get('app_show', '1'),
    'show_verify' => Env::get('app_show_verify', '0'),
    'search' => Env::get('app_search', '1'),
    'search_verify' => Env::get('app_search_verify', '0'),
    'search_len' => Env::get('app_search_len', ''),
    'search_timespan' => Env::get('app_search_timespan', '3'),
    'search_vod_rule' => Env::get('app_search_vod_rule', 'vod_en|vod_sub'),
    'search_art_rule' => Env::get('app_search_art_rule', 'art_en|art_sub'),
    'vod_search_optimise' => Env::get('app_vod_search_optimise', 'frontend|collect'),
    'vod_search_optimise_cache_minutes' => Env::get('app_vod_search_optimise_cache_minutes', 20160),
    'copyright_status' => Env::get('app_copyright_status', '1'),
    'copyright_notice' => Env::get('app_copyright_notice', '该视频由于版权限制，暂不提供播放。'),
    'browser_junmp' => Env::get('app_browser_junmp', '0'),
    'page_404' => Env::get('app_page_404', '404'),
    'player_sort' => Env::get('app_player_sort', '1'),
    'encrypt' => Env::get('app_encrypt', '0'),
    'search_hot' => Env::get('app_search_hot', '变形金刚,火影忍者,复仇者联盟,战狼,红海行动'),
    'search_suggest_min_chars' => Env::get('app_search_suggest_min_chars', '2'),
    'search_suggest_cache_sec' => Env::get('app_search_suggest_cache_sec', '180'),
    'search_suggest_rate_ip' => Env::get('app_search_suggest_rate_ip', '90'),
    'search_suggest_rate_window_sec' => Env::get('app_search_suggest_rate_window_sec', '60'),
    'search_suggest_order' => Env::get('app_search_suggest_order', 'popular'),
    'search_query_log' => Env::get('app_search_query_log', '1'),
    'search_query_log_dedupe_sec' => Env::get('app_search_query_log_dedupe_sec', '120'),
    'search_hot_cache_sec' => Env::get('app_search_hot_cache_sec', '600'),
    'art_extend_class' => Env::get('app_art_extend_class', '段子手,私房话,八卦精,爱生活,汽车迷,科技咖,美食家,辣妈帮'),
    'vod_extend_class' => Env::get('app_vod_extend_class', '爱情,动作,喜剧,战争,科幻,剧情,武侠,冒险,枪战,恐怖,微电影,其它'),
    'vod_extend_state' => Env::get('app_vod_extend_state', '正片,预告片,花絮'),
    'vod_extend_version' => Env::get('app_vod_extend_version', '高清版,剧场版,抢先版,OVA,TV,影院版'),
    'vod_extend_area' => Env::get('app_vod_extend_area', '大陆,香港,台湾,美国,韩国,日本,泰国,新加坡,马来西亚,印度,英国,法国,加拿大,西班牙,俄罗斯,其它'),
    'vod_extend_lang' => Env::get('app_vod_extend_lang', '国语,英语,粤语,闽南语,韩语,日语,法语,德语,其它'),
    'vod_extend_year' => Env::get('app_vod_extend_year', '2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000'),
    'vod_extend_weekday' => Env::get('app_vod_extend_weekday', '一,二,三,四,五,六,日'),
    'actor_extend_area' => Env::get('app_actor_extend_area', '大陆,香港,台湾,美国,韩国,日本,泰国,新加坡,马来西亚,印度,英国,法国,加拿大,西班牙,俄罗斯,其它'),
    'filter_words' => Env::get('app_filter_words', 'www,http,com,net'),
    'extra_var' => Env::get('app_extra_var', ''),
    'collect_timespan' => Env::get('app_collect_timespan', '3'),
    'pagesize' => Env::get('app_pagesize', '20'),
    'makesize' => Env::get('app_makesize', '30'),
    'admin_login_verify' => Env::get('app_admin_login_verify', '1'),
    'editor' => Env::get('app_editor', 'Ueditor'),
    'lang' => Env::get('app_lang', 'zh-cn'),
    'security_xss_input' => Env::get('app_security_xss_input', '1'),
    'security_xss_admin' => Env::get('app_security_xss_admin', '0'),
    'security_xss_skip_json' => Env::get('app_security_xss_skip_json', '1'),
    'security_headers_base' => Env::get('app_security_headers_base', '1'),
    'security_csp' => Env::get('app_security_csp', '0'),
    'security_csp_policy' => Env::get('app_security_csp_policy', ''),
    'security_csp_report_uri' => Env::get('app_security_csp_report_uri', ''),
    'security_csrf_admin' => Env::get('app_security_csrf_admin', '0'),
    'security_csrf_admin_exempt' => Env::get('app_security_csrf_admin_exempt', 'upload/*'),
    'security_csrf_http_code' => Env::get('app_security_csrf_http_code', '403'),
    'api_jwt_enabled' => Env::get('app_api_jwt_enabled', '0'),
    'api_jwt_secret' => Env::get('app_api_jwt_secret', ''),
    'api_jwt_ttl' => Env::get('app_api_jwt_ttl', '7200'),
    'api_jwt_iss' => Env::get('app_api_jwt_iss', 'maccms'),
    'admin_audit_enabled' => Env::get('app_admin_audit_enabled', '0'),
    'admin_audit_get' => Env::get('app_admin_audit_get', '0'),
    'admin_audit_encrypt' => Env::get('app_admin_audit_encrypt', '0'),
    'admin_audit_crypto_secret' => Env::get('app_admin_audit_crypto_secret', ''),
    'admin_audit_extra_redact' => Env::get('app_admin_audit_extra_redact', ''),
    'anti_scrape_api_enabled' => Env::get('app_anti_scrape_api_enabled', '0'),
    'anti_scrape_api_window_sec' => Env::get('app_anti_scrape_api_window_sec', '60'),
    'anti_scrape_api_max' => Env::get('app_anti_scrape_api_max', '120'),
    'anti_scrape_api_search_window_sec' => Env::get('app_anti_scrape_api_search_window_sec', '60'),
    'anti_scrape_api_search_max' => Env::get('app_anti_scrape_api_search_max', '30'),
    'anti_scrape_api_exempt' => Env::get('app_anti_scrape_api_exempt', 'timming/index'),
    'anti_scrape_index_enabled' => Env::get('app_anti_scrape_index_enabled', '0'),
    'anti_scrape_index_window_sec' => Env::get('app_anti_scrape_index_window_sec', '60'),
    'anti_scrape_index_max' => Env::get('app_anti_scrape_index_max', '90'),
  ),
  'user' => array (
    'status' => Env::get('user_status', '1'),
    'reg_open' => Env::get('user_reg_open', '1'),
    'reg_status' => Env::get('user_reg_status', '1'),
    'reg_phone_sms' => Env::get('user_reg_phone_sms', '0'),
    'reg_email_sms' => Env::get('user_reg_email_sms', '0'),
    'reg_verify' => Env::get('user_reg_verify', '0'),
    'login_verify' => Env::get('user_login_verify', '0'),
    'reg_points' => Env::get('user_reg_points', '10'),
    'reg_num' => Env::get('user_reg_num', '1'),
    'invite_reg_points' => Env::get('user_invite_reg_points', '10'),
    'invite_visit_points' => Env::get('user_invite_visit_points', '1'),
    'invite_visit_num' => Env::get('user_invite_visit_num', '1'),
    'reward_status' => Env::get('user_reward_status', '1'),
    'reward_ratio' => Env::get('user_reward_ratio', '10'),
    'reward_ratio_2' => Env::get('user_reward_ratio_2', '30'),
    'reward_ratio_3' => Env::get('user_reward_ratio_3', '50'),
    'cash_status' => Env::get('user_cash_status', '1'),
    'cash_ratio' => Env::get('user_cash_ratio', '100'),
    'cash_min' => Env::get('user_cash_min', '1'),
    'trysee' => Env::get('user_trysee', '0'),
    'vod_points_type' => Env::get('user_vod_points_type', '1'),
    'art_points_type' => Env::get('user_art_points_type', '1'),
    'portrait_status' => Env::get('user_portrait_status', '1'),
    'portrait_size' => Env::get('user_portrait_size', '100x100'),
    'filter_words' => Env::get('user_filter_words', 'admin,cao,sex,xxx'),
  ),
  'gbook' => array (
    'status' => Env::get('gbook_status', '1'),
    'audit' => Env::get('gbook_audit', '0'),
    'login' => Env::get('gbook_login', '0'),
    'verify' => Env::get('gbook_verify', '1'),
    'pagesize' => Env::get('gbook_pagesize', '20'),
    'timespan' => Env::get('gbook_timespan', '3'),
  ),
  'comment' => array (
    'status' => Env::get('comment_status', '1'),
    'audit' => Env::get('comment_audit', '0'),
    'login' => Env::get('comment_login', '0'),
    'verify' => Env::get('comment_verify', '1'),
    'pagesize' => Env::get('comment_pagesize', '20'),
    'timespan' => Env::get('comment_timespan', '3'),
  ),
  'upload' => array (
    'img_key' => Env::get('upload_img_key', 'baidu|douban|tvmao'),
    'img_api' => Env::get('upload_img_api', '/img.php?url='),
    'thumb' => Env::get('upload_thumb', '0'),
    'thumb_size' => Env::get('upload_thumb_size', '300x300'),
    'thumb_type' => Env::get('upload_thumb_type', '1'),
    'watermark' => Env::get('upload_watermark', '0'),
    'watermark_location' => Env::get('upload_watermark_location', '7'),
    'watermark_content' => Env::get('upload_watermark_content', 'test'),
    'watermark_size' => Env::get('upload_watermark_size', '40'),
    'watermark_color' => Env::get('upload_watermark_color', '#FF0000'),
    'protocol' => Env::get('upload_protocol', 'http'),
    'mode' => Env::get('upload_mode', 'local'),
    'remoteurl' => Env::get('upload_remoteurl', 'http://img.test.com/'),
    'api' => array (
      'ftp' => array (
        'host' => Env::get('upload_api_ftp_host', ''),
        'port' => Env::get('upload_api_ftp_port', '21'),
        'user' => Env::get('upload_api_ftp_user', 'test'),
        'pwd' => Env::get('upload_api_ftp_pwd', 'test'),
        'path' => Env::get('upload_api_ftp_path', '/'),
        'url' => Env::get('upload_api_ftp_url', ''),
      ),
      'qiniu' => array (
        'bucket' => Env::get('upload_api_qiniu_bucket', ''),
        'accesskey' => Env::get('upload_api_qiniu_accesskey', ''),
        'secretkey' => Env::get('upload_api_qiniu_secretkey', ''),
        'url' => Env::get('upload_api_qiniu_url', ''),
      ),
      'uomg' => array (
        'openid' => Env::get('upload_api_uomg_openid', ''),
        'key' => Env::get('upload_api_uomg_key', ''),
        'type' => Env::get('upload_api_uomg_type', 'sogou'),
      ),
      'upyun' => array (
        'bucket' => Env::get('upload_api_upyun_bucket', ''),
        'username' => Env::get('upload_api_upyun_username', ''),
        'pwd' => Env::get('upload_api_upyun_pwd', ''),
        'url' => Env::get('upload_api_upyun_url', ''),
      ),
      'weibo' => array (
        'user' => Env::get('upload_api_weibo_user', ''),
        'pwd' => Env::get('upload_api_weibo_pwd', ''),
        'size' => Env::get('upload_api_weibo_size', 'large'),
        'cookie' => Env::get('upload_api_weibo_cookie', ''),
        'time' => Env::get('upload_api_weibo_time', '1546239694'),
      ),
    ),
  ),
  'interface' => array (
    'status' => Env::get('interface_status', 0),
    'pass' => Env::get('interface_pass', 'E4UMURASOGWCLH8C'),
    'vodtype' => Env::get('interface_vodtype', '动作片=动作'),
    'arttype' => Env::get('interface_arttype', '头条=头条'),
    'actortype' => Env::get('interface_actortype', ''),
    'websitetype' => Env::get('interface_websitetype', ''),
  ),
  'pay' => array (
    'min' => Env::get('pay_min', '10'),
    'scale' => Env::get('pay_scale', '1'),
    'card' => array (
      'url' => Env::get('pay_card_url', ''),
    ),
    'alipay' => array (
      'account' => Env::get('pay_alipay_account', '111'),
      'appid' => Env::get('pay_alipay_appid', ''),
      'appkey' => Env::get('pay_alipay_appkey', ''),
    ),
    'codepay' => array (
      'appid' => Env::get('pay_codepay_appid', '40625'),
      'appkey' => Env::get('pay_codepay_appkey', ''),
      'type' => Env::get('pay_codepay_type', '1,2'),
      'act' => Env::get('pay_codepay_act', '0'),
    ),
    'weixin' => array (
      'appid' => Env::get('pay_weixin_appid', '222'),
      'mchid' => Env::get('pay_weixin_mchid', ''),
      'appkey' => Env::get('pay_weixin_appkey', ''),
    ),
    'zhapay' => array (
      'appid' => Env::get('pay_zhapay_appid', '18039'),
      'appkey' => Env::get('pay_zhapay_appkey', ''),
      'type' => Env::get('pay_zhapay_type', '1,2'),
      'act' => Env::get('pay_zhapay_act', '2'),
    ),
  ),
  'collect' => array (
    'vod' => array (
      'status' => Env::get('collect_vod_status', '1'),
      'hits_start' => Env::get('collect_vod_hits_start', '1'),
      'hits_end' => Env::get('collect_vod_hits_end', '1000'),
      'updown_start' => Env::get('collect_vod_updown_start', '1'),
      'updown_end' => Env::get('collect_vod_updown_end', '1000'),
      'score' => Env::get('collect_vod_score', '1'),
      'pic' => Env::get('collect_vod_pic', '0'),
      'tag' => Env::get('collect_vod_tag', '0'),
      'class_filter' => Env::get('collect_vod_class_filter', '1'),
      'psename' => Env::get('collect_vod_psename', '1'),
      'psernd' => Env::get('collect_vod_psernd', '0'),
      'psesyn' => Env::get('collect_vod_psesyn', '0'),
      'urlrole' => Env::get('collect_vod_urlrole', '0'),
      'inrule' => Env::get('collect_vod_inrule', ',f,g'),
      'uprule' => Env::get('collect_vod_uprule', ',a'),
      'filter' => Env::get('collect_vod_filter', '色戒,色即是空'),
      'namewords' => Env::get('collect_vod_namewords', '第1季=第一季#第2季=第二季#第3季=第三季#第4季=第四季'),
      'thesaurus' => Env::get('collect_vod_thesaurus', ' ='),
      'words' => Env::get('collect_vod_words', 'aaa#bbb#ccc#ddd#eee'),
    ),
    'art' => array (
      'status' => Env::get('collect_art_status', '1'),
      'hits_start' => Env::get('collect_art_hits_start', '1'),
      'hits_end' => Env::get('collect_art_hits_end', '1000'),
      'updown_start' => Env::get('collect_art_updown_start', '1'),
      'updown_end' => Env::get('collect_art_updown_end', '1000'),
      'score' => Env::get('collect_art_score', '1'),
      'pic' => Env::get('collect_art_pic', '0'),
      'tag' => Env::get('collect_art_tag', '0'),
      'psernd' => Env::get('collect_art_psernd', '0'),
      'psesyn' => Env::get('collect_art_psesyn', '0'),
      'inrule' => Env::get('collect_art_inrule', ',b'),
      'uprule' => Env::get('collect_art_uprule', ',a,d'),
      'filter' => Env::get('collect_art_filter', '无奈的人'),
      'thesaurus' => Env::get('collect_art_thesaurus', ''),
      'words' => Env::get('collect_art_words', ''),
    ),
    'actor' => array (
      'status' => Env::get('collect_actor_status', '0'),
      'hits_start' => Env::get('collect_actor_hits_start', '1'),
      'hits_end' => Env::get('collect_actor_hits_end', '999'),
      'updown_start' => Env::get('collect_actor_updown_start', '1'),
      'updown_end' => Env::get('collect_actor_updown_end', '999'),
      'score' => Env::get('collect_actor_score', '0'),
      'pic' => Env::get('collect_actor_pic', '0'),
      'psernd' => Env::get('collect_actor_psernd', '0'),
      'psesyn' => Env::get('collect_actor_psesyn', '0'),
      'uprule' => Env::get('collect_actor_uprule', ',a,b,c'),
      'filter' => Env::get('collect_actor_filter', '无奈的人'),
      'thesaurus' => Env::get('collect_actor_thesaurus', ''),
      'words' => Env::get('collect_actor_words', ''),
      'inrule' => Env::get('collect_actor_inrule', ',a'),
    ),
    'role' => array (
      'status' => Env::get('collect_role_status', '0'),
      'hits_start' => Env::get('collect_role_hits_start', '1'),
      'hits_end' => Env::get('collect_role_hits_end', '999'),
      'updown_start' => Env::get('collect_role_updown_start', '1'),
      'updown_end' => Env::get('collect_role_updown_end', '999'),
      'score' => Env::get('collect_role_score', '0'),
      'pic' => Env::get('collect_role_pic', '0'),
      'psernd' => Env::get('collect_role_psernd', '0'),
      'psesyn' => Env::get('collect_role_psesyn', '0'),
      'uprule' => Env::get('collect_role_uprule', ',a,b,c'),
      'filter' => Env::get('collect_role_filter', ''),
      'thesaurus' => Env::get('collect_role_thesaurus', ''),
      'words' => Env::get('collect_role_words', ''),
      'inrule' => Env::get('collect_role_inrule', ',a'),
    ),
    'website' => array (
      'status' => Env::get('collect_website_status', '0'),
      'hits_start' => Env::get('collect_website_hits_start', ''),
      'hits_end' => Env::get('collect_website_hits_end', ''),
      'updown_start' => Env::get('collect_website_updown_start', ''),
      'updown_end' => Env::get('collect_website_updown_end', ''),
      'score' => Env::get('collect_website_score', '0'),
      'pic' => Env::get('collect_website_pic', '0'),
      'psernd' => Env::get('collect_website_psernd', '0'),
      'psesyn' => Env::get('collect_website_psesyn', '0'),
      'filter' => Env::get('collect_website_filter', ''),
      'thesaurus' => Env::get('collect_website_thesaurus', ''),
      'words' => Env::get('collect_website_words', ''),
      'inrule' => Env::get('collect_website_inrule', ',a'),
      'uprule' => Env::get('collect_website_uprule', ','),
    ),
    'comment' => array (
      'status' => Env::get('collect_comment_status', '0'),
      'updown_start' => Env::get('collect_comment_updown_start', '1'),
      'updown_end' => Env::get('collect_comment_updown_end', '100'),
      'psernd' => Env::get('collect_comment_psernd', '0'),
      'psesyn' => Env::get('collect_comment_psesyn', '0'),
      'inrule' => Env::get('collect_comment_inrule', ',b'),
      'filter' => Env::get('collect_comment_filter', ''),
      'thesaurus' => Env::get('collect_comment_thesaurus', ''),
      'words' => Env::get('collect_comment_words', ''),
      'uprule' => Env::get('collect_comment_uprule', ','),
    ),
    'manga' => array (
      'status' => Env::get('collect_manga_status', '0'),
      'hits_start' => Env::get('collect_manga_hits_start', ''),
      'hits_end' => Env::get('collect_manga_hits_end', ''),
      'updown_start' => Env::get('collect_manga_updown_start', ''),
      'updown_end' => Env::get('collect_manga_updown_end', ''),
      'score' => Env::get('collect_manga_score', '0'),
      'pic' => Env::get('collect_manga_pic', '0'),
      'psernd' => Env::get('collect_manga_psernd', '0'),
      'psesyn' => Env::get('collect_manga_psesyn', '0'),
      'filter' => Env::get('collect_manga_filter', ''),
      'thesaurus' => Env::get('collect_manga_thesaurus', ''),
      'words' => Env::get('collect_manga_words', ''),
      'inrule' => Env::get('collect_manga_inrule', ',a'),
      'uprule' => Env::get('collect_manga_uprule', ',a'),
    ),
  ),
  'api' => array (
    'vod' => array (
      'status' => Env::get('api_vod_status', '1'),
      'charge' => Env::get('api_vod_charge', '0'),
      'detail_inc_hits' => Env::get('api_vod_detail_inc_hits', '1'),
      'pagesize' => Env::get('api_vod_pagesize', '20'),
      'imgurl' => Env::get('api_vod_imgurl', 'http://img.test.com/'),
      'typefilter' => Env::get('api_vod_typefilter', ''),
      'datafilter' => Env::get('api_vod_datafilter', ' vod_status=1'),
      'cachetime' => Env::get('api_vod_cachetime', ''),
      'from' => Env::get('api_vod_from', ''),
      'auth' => Env::get('api_vod_auth', 'test.com#163.com'),
    ),
    'art' => array (
      'status' => Env::get('api_art_status', '1'),
      'charge' => Env::get('api_art_charge', '0'),
      'pagesize' => Env::get('api_art_pagesize', '20'),
      'imgurl' => Env::get('api_art_imgurl', ''),
      'typefilter' => Env::get('api_art_typefilter', ''),
      'datafilter' => Env::get('api_art_datafilter', 'art_status=1'),
      'cachetime' => Env::get('api_art_cachetime', ''),
      'auth' => Env::get('api_art_auth', ''),
    ),
    'actor' => array (
      'status' => Env::get('api_actor_status', '1'),
      'charge' => Env::get('api_actor_charge', '0'),
      'pagesize' => Env::get('api_actor_pagesize', '20'),
      'imgurl' => Env::get('api_actor_imgurl', ''),
      'typefilter' => Env::get('api_actor_typefilter', ''),
      'datafilter' => Env::get('api_actor_datafilter', 'actor_status=1'),
      'cachetime' => Env::get('api_actor_cachetime', ''),
      'auth' => Env::get('api_actor_auth', ''),
    ),
    'role' => array (
      'status' => Env::get('api_role_status', '1'),
      'charge' => Env::get('api_role_charge', '0'),
      'pagesize' => Env::get('api_role_pagesize', '20'),
      'imgurl' => Env::get('api_role_imgurl', ''),
      'typefilter' => Env::get('api_role_typefilter', ''),
      'datafilter' => Env::get('api_role_datafilter', 'role_status=1'),
      'cachetime' => Env::get('api_role_cachetime', ''),
      'auth' => Env::get('api_role_auth', ''),
    ),
    'website' => array (
      'status' => Env::get('api_website_status', '1'),
      'charge' => Env::get('api_website_charge', '0'),
      'pagesize' => Env::get('api_website_pagesize', '20'),
      'imgurl' => Env::get('api_website_imgurl', ''),
      'typefilter' => Env::get('api_website_typefilter', ''),
      'datafilter' => Env::get('api_website_datafilter', 'website_status=1'),
      'cachetime' => Env::get('api_website_cachetime', ''),
      'auth' => Env::get('api_website_auth', ''),
    ),
    'manga' => array (
      'status' => Env::get('api_manga_status', '1'),
      'charge' => Env::get('api_manga_charge', '0'),
      'pagesize' => Env::get('api_manga_pagesize', '20'),
      'imgurl' => Env::get('api_manga_imgurl', ''),
      'typefilter' => Env::get('api_manga_typefilter', ''),
      'datafilter' => Env::get('api_manga_datafilter', 'manga_status=1'),
      'cachetime' => Env::get('api_manga_cachetime', ''),
      'auth' => Env::get('api_manga_auth', ''),
    ),
    'publicapi' => array (
      'status' => Env::get('api_publicapi_status', '1'),
      'charge' => Env::get('api_publicapi_charge', '0'),
      'auth' => Env::get('api_publicapi_auth', ''),
    ),
    'analytics' => array (
      'rate_window_sec' => Env::get('api_analytics_rate_window_sec', '60'),
      'rate_limit_visitor' => Env::get('api_analytics_rate_limit_visitor', '60'),
      'rate_limit_ip' => Env::get('api_analytics_rate_limit_ip', '120'),
    ),
  ),
  'connect' => array (
    'qq' => array (
      'status' => Env::get('connect_qq_status', '0'),
      'key' => Env::get('connect_qq_key', 'aa'),
      'secret' => Env::get('connect_qq_secret', 'bb'),
    ),
    'weixin' => array (
      'status' => Env::get('connect_weixin_status', '0'),
      'key' => Env::get('connect_weixin_key', 'cc'),
      'secret' => Env::get('connect_weixin_secret', 'dd'),
    ),
  ),
  'weixin' => array (
    'status' => Env::get('weixin_status', '1'),
    'duijie' => Env::get('weixin_duijie', 'wx.test.com'),
    'sousuo' => Env::get('weixin_sousuo', 'wx.test.com'),
    'token' => Env::get('weixin_token', 'qweqwe'),
    'guanzhu' => Env::get('weixin_guanzhu', '欢迎关注'),
    'wuziyuan' => Env::get('weixin_wuziyuan', '没找到资源，请更换关键词或等待更新'),
    'wuziyuanlink' => Env::get('weixin_wuziyuanlink', 'demo.test.com'),
    'bofang' => Env::get('weixin_bofang', '0'),
    'msgtype' => Env::get('weixin_msgtype', '0'),
    'gjc1' => Env::get('weixin_gjc1', '关键词1'),
    'gjcm1' => Env::get('weixin_gjcm1', '长城'),
    'gjci1' => Env::get('weixin_gjci1', 'http://img.aolusb.com/im/201610/2016101222371965996.jpg'),
    'gjcl1' => Env::get('weixin_gjcl1', 'http://www.loldytt.com/Dongzuodianying/CC/'),
    'gjc2' => Env::get('weixin_gjc2', '关键词2'),
    'gjcm2' => Env::get('weixin_gjcm2', '生化危机6'),
    'gjci2' => Env::get('weixin_gjci2', 'http://img.aolusb.com/im/201702/20172711214866248.jpg'),
    'gjcl2' => Env::get('weixin_gjcl2', 'http://www.loldytt.com/Kehuandianying/SHWJ6ZZ/'),
    'gjc3' => Env::get('weixin_gjc3', '关键词3'),
    'gjcm3' => Env::get('weixin_gjcm3', '湄公河行动'),
    'gjci3' => Env::get('weixin_gjci3', 'http://img.aolusb.com/im/201608/201681719561972362.jpg'),
    'gjcl3' => Env::get('weixin_gjcl3', 'http://www.loldytt.com/Dongzuodianying/GHXD/'),
    'gjc4' => Env::get('weixin_gjc4', '关键词4'),
    'gjcm4' => Env::get('weixin_gjcm4', '王牌逗王牌'),
    'gjci4' => Env::get('weixin_gjci4', 'http://img.aolusb.com/im/201601/201612723554344882.jpg'),
    'gjcl4' => Env::get('weixin_gjcl4', 'http://www.loldytt.com/Xijudianying/WPDWP/'),
  ),
  'view' => array (
    'index' => Env::get('view_index', '0'),
    'map' => Env::get('view_map', '0'),
    'search' => Env::get('view_search', '0'),
    'rss' => Env::get('view_rss', '0'),
    'label' => Env::get('view_label', '0'),
    'vod_type' => Env::get('view_vod_type', '0'),
    'vod_show' => Env::get('view_vod_show', '0'),
    'art_type' => Env::get('view_art_type', '0'),
    'art_show' => Env::get('view_art_show', '0'),
    'topic_index' => Env::get('view_topic_index', '0'),
    'topic_detail' => Env::get('view_topic_detail', '0'),
    'vod_detail' => Env::get('view_vod_detail', '0'),
    'vod_play' => Env::get('view_vod_play', '0'),
    'vod_down' => Env::get('view_vod_down', '0'),
    'art_detail' => Env::get('view_art_detail', '0'),
  ),
  'path' => array (
    'topic_index' => Env::get('path_topic_index', 'topic/index'),
    'topic_detail' => Env::get('path_topic_detail', 'topic/{id}/index'),
    'vod_type' => Env::get('path_vod_type', 'vodtypehtml/{id}/index'),
    'vod_detail' => Env::get('path_vod_detail', 'vodhtml/{id}/index'),
    'vod_play' => Env::get('path_vod_play', 'vodplayhtml/{id}/index'),
    'vod_down' => Env::get('path_vod_down', 'voddownhtml/{id}/index'),
    'art_type' => Env::get('path_art_type', 'arttypehtml/{id}/index'),
    'art_detail' => Env::get('path_art_detail', 'arthtml/{id}/index'),
    'page_sp' => Env::get('path_page_sp', '_'),
    'suffix' => Env::get('path_suffix', 'html'),
  ),
  'rewrite' => array (
    'suffix_hide' => Env::get('rewrite_suffix_hide', '0'),
    'route_status' => Env::get('rewrite_route_status', '0'),
    'status' => Env::get('rewrite_status', '0'),
    'encode_key' => Env::get('rewrite_encode_key', 'abcdefg'),
    'encode_len' => Env::get('rewrite_encode_len', '6'),
    'vod_id' => Env::get('rewrite_vod_id', '0'),
    'art_id' => Env::get('rewrite_art_id', '0'),
    'type_id' => Env::get('rewrite_type_id', '0'),
    'topic_id' => Env::get('rewrite_topic_id', '0'),
    'actor_id' => Env::get('rewrite_actor_id', '0'),
    'role_id' => Env::get('rewrite_role_id', '0'),
    'website_id' => Env::get('rewrite_website_id', '0'),
    'route' => 'map   => map/index
rss/index   => rss/index
rss/baidu => rss/baidu
rss/google => rss/google
rss/sogou => rss/sogou
rss/so => rss/so
rss/bing => rss/bing
rss/sm => rss/sm

index-<page?>   => index/index

gbook-<page?>   => gbook/index
gbook$   => gbook/index

topic-<page?>   => topic/index
topic$  => topic/index
topicdetail-<id>   => topic/detail

actor-<page?>   => actor/index
actor$ => actor/index
actordetail-<id>   => actor/detail
actorshow/<area?>-<blood?>-<by?>-<letter?>-<level?>-<order?>-<page?>-<sex?>-<starsign?>   => actor/show

role-<page?>   => role/index
role$ => role/index
roledetail-<id>   => role/detail
roleshow/<by?>-<letter?>-<level?>-<order?>-<page?>-<rid?>   => role/show


vodtype/<id>-<page?>   => vod/type
vodtype/<id>   => vod/type
voddetail/<id>   => vod/detail
vodrss-<id>   => vod/rss
vodplay/<id>-<sid>-<nid>   => vod/play
voddown/<id>-<sid>-<nid>   => vod/down
vodshow/<id>-<area?>-<by?>-<class?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<state?>-<tag?>-<year?>   => vod/show
vodsearch/<wd?>-<actor?>-<area?>-<by?>-<class?>-<director?>-<lang?>-<letter?>-<level?>-<order?>-<page?>-<state?>-<tag?>-<year?>   => vod/search
vodplot/<id>-<page?>   => vod/plot
vodplot/<id>   => vod/plot


arttype/<id>-<page?>   => art/type
arttype/<id>   => art/type
artshow-<id>   => art/show
artdetail-<id>-<page?>   => art/detail
artdetail-<id>   => art/detail
artrss-<id>-<page>   => art/rss
artshow/<id>-<by?>-<class?>-<level?>-<letter?>-<order?>-<page?>-<tag?>   => art/show
artsearch/<wd?>-<by?>-<class?>-<level?>-<letter?>-<order?>-<page?>-<tag?>   => art/search

label-<file> => label/index

plotdetail/<id>-<page?>   => plot/plot
plotdetail/<id>   => plot/detail',
  ),
  'email' => array (
    'type' => Env::get('email_type', 'Phpmailer'),
    'time' => Env::get('email_time', '5'),
    'nick' => Env::get('email_nick', 'test'),
    'test' => Env::get('email_test', 'test@qq.com'),
    'tpl' => array (
      'test_title' => Env::get('email_tpl_test_title', '【{$maccms.site_name}】测试邮件标题'),
      'test_body' => Env::get('email_tpl_test_body', '【{$maccms.site_name}】当您看到这封邮件说明邮件配置正确了！感谢支持开源程序！'),
      'user_reg_title' => Env::get('email_tpl_user_reg_title', '【{$maccms.site_name}】的会员您好，请认真阅读邮件正文并按要求操作完成注册'),
      'user_reg_body' => Env::get('email_tpl_user_reg_body', '【{$maccms.site_name}】的会员您好，注册验证码为：{$code}，请在{$time}分钟内完成验证。'),
      'user_bind_title' => Env::get('email_tpl_user_bind_title', '【{$maccms.site_name}】的会员您好，请认真阅读邮件正文并按要求操作完成绑定'),
      'user_bind_body' => Env::get('email_tpl_user_bind_body', '【{$maccms.site_name}】的会员您好，绑定验证码为：{$code}，请在{$time}分钟内完成验证。'),
      'user_findpass_title' => Env::get('email_tpl_user_findpass_title', '【{$maccms.site_name}】的会员您好，请认真阅读邮件正文并按要求操作完成找回'),
      'user_findpass_body' => Env::get('email_tpl_user_findpass_body', '【{$maccms.site_name}】的会员您好，找回验证码为：{$code}，请在{$time}分钟内完成验证。'),
    ),
    'phpmailer' => array (
      'host' => Env::get('email_phpmailer_host', 'smtp.qq.com'),
      'port' => Env::get('email_phpmailer_port', '587'),
      'secure' => Env::get('email_phpmailer_secure', 'tsl'),
      'username' => Env::get('email_phpmailer_username', 'test@qq.com'),
      'password' => Env::get('email_phpmailer_password', 'test'),
    ),
  ),
  'play' => array (
    'width' => Env::get('play_width', '100%'),
    'height' => Env::get('play_height', '100%'),
    'widthmob' => Env::get('play_widthmob', '100%'),
    'heightmob' => Env::get('play_heightmob', '100%'),
    'widthpop' => Env::get('play_widthpop', '0'),
    'heightpop' => Env::get('play_heightpop', '600'),
    'second' => Env::get('play_second', '5'),
    'prestrain' => Env::get('play_prestrain', '//union.maccms.la/html/prestrain.html'),
    'buffer' => Env::get('play_buffer', '//union.maccms.la/html/buffer.html'),
    'parse' => Env::get('play_parse', ''),
    'autofull' => Env::get('play_autofull', '0'),
    'showtop' => Env::get('play_showtop', '1'),
    'showlist' => Env::get('play_showlist', '1'),
    'flag' => Env::get('play_flag', '0'),
    'colors' => Env::get('play_colors', '000000,F6F6F6,F6F6F6,333333,666666,FFFFF,FF0000,2c2c2c,ffffff,a3a3a3,2c2c2c,adadad,adadad,48486c,fcfcfc'),
  ),
  'sms' => array (
    'type' => Env::get('sms_type', ''),
    'sign' => Env::get('sms_sign', '我的网站'),
    'tpl_code_reg' => Env::get('sms_tpl_code_reg', 'SMS_144850895'),
    'tpl_code_bind' => Env::get('sms_tpl_code_bind', 'SMS_144940283'),
    'tpl_code_findpass' => Env::get('sms_tpl_code_findpass', 'SMS_144851023'),
    'aliyun' => array (
      'appid' => Env::get('sms_aliyun_appid', ''),
      'appkey' => Env::get('sms_aliyun_appkey', ''),
    ),
    'qcloud' => array (
      'appid' => Env::get('sms_qcloud_appid', ''),
      'appkey' => Env::get('sms_qcloud_appkey', ''),
    ),
  ),
  'extra' => array (
  ),
  'seo' => array (
    'vod' => array (
      'name' => Env::get('seo_vod_name', '视频首页'),
      'key' => Env::get('seo_vod_key', '短视频,搞笑视频,视频分享,免费视频,在线视频,预告片'),
      'des' => Env::get('seo_vod_des', '提供最新最快的视频分享数据'),
    ),
    'art' => array (
      'name' => Env::get('seo_art_name', '文章首页'),
      'key' => Env::get('seo_art_key', '新闻资讯,娱乐新闻,八卦娱乐,狗仔队,重大事件'),
      'des' => Env::get('seo_art_des', '提供最新最快的新闻资讯'),
    ),
    'actor' => array (
      'name' => Env::get('seo_actor_name', '演员首页'),
      'key' => Env::get('seo_actor_key', '大陆明星,港台明星,日韩明星,欧美明星,最火明星'),
      'des' => Env::get('seo_actor_des', '明星个人信息介绍'),
    ),
    'role' => array (
      'name' => Env::get('seo_role_name', '角色首页'),
      'key' => Env::get('seo_role_key', '电影角色,电视剧角色,动漫角色,综艺角色'),
      'des' => Env::get('seo_role_des', '角色人物介绍'),
    ),
    'plot' => array (
      'name' => Env::get('seo_plot_name', '剧情首页'),
      'key' => Env::get('seo_plot_key', '剧情连载,剧情更新,剧情前瞻,剧情完结'),
      'des' => Env::get('seo_plot_des', '提供最新的剧情信息'),
    ),
  ),
  'meilisearch' => array (
    'enabled' => Env::get('meilisearch_enabled', '0'),
    'host' => Env::get('meilisearch_host', 'http://127.0.0.1:7700'),
    'api_key' => Env::get('meilisearch_api_key', ''),
    'index_uid' => Env::get('meilisearch_index_uid', 'maccms_contents'),
    'timeout' => Env::get('meilisearch_timeout', '8'),
    'ssl_verify' => Env::get('meilisearch_ssl_verify', '1'),
    'sync_on_save' => Env::get('meilisearch_sync_on_save', '1'),
    'search_only_wd' => Env::get('meilisearch_search_only_wd', '1'),
  ),
  'urlsend' => array (
    'baidu' => array (
      'token' => Env::get('urlsend_baidu_token', '111'),
    ),
    'baidufast' => array (
      'token' => Env::get('urlsend_baidufast_token', '222'),
    ),
  ),
);
